apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
spec:
  selector:
    app: todo-backend
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  selector:
    matchLabels:
      app: todo-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: kairzhanov/todo-backend:latest
        ports:
        - containerPort: 5000